### PR TITLE
Zaki/sommelier-2-state-export

### PR DESCRIPTION
**Pull request by zmanian**
Working branch for creating the sommelier-3 genesis to recover from the failed sommeier-2 upgrade

### CODE REVIEW

**Review by jackzampolin — APPROVED** [review]

**Comment by zmanian** [comment]
QA steps needed

This is missing an allocation genesis state.

1. Start the Somm-v3 binary with this genesis and check if it panics.
2. Simulate a testnet v2 to v3 upgrade by manually editing a export in this way.
3. Compare this genesis to a fresh Somm-v3 init.

**Comment by jackzampolin** [comment]
```
11:42AM INF starting ABCI with Tendermint
11:42AM ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.45). Please explicitly put the desired minimum-gas-prices in your app.toml.
11:42AM INF Starting multiAppConn service impl=multiAppConn module=proxy
11:42AM INF Starting localClient service connection=query impl=localClient module=abci-client
11:42AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
11:42AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
11:42AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
11:42AM INF Starting EventBus service impl=EventBus module=events
11:42AM INF Starting PubSub service impl=PubSub module=pubsub
11:42AM INF Starting IndexerService service impl=IndexerService module=txindex
11:42AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v3.0.6
11:42AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
11:42AM INF asserting crisis invariants inv=0/11 module=x/crisis name=gov/module-account
11:42AM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/nonnegative-outstanding
11:42AM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/can-withdraw
11:42AM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/reference-count
11:42AM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/module-account
11:42AM INF asserting crisis invariants inv=5/11 module=x/crisis name=bank/nonnegative-outstanding
11:42AM INF asserting crisis invariants inv=6/11 module=x/crisis name=bank/total-supply
11:42AM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
11:42AM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
11:42AM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
11:42AM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
11:42AM INF asserted all invariants duration=5.63325 height=1936000 module=x/crisis
panic: Invalid delegate key in Genesis!

goroutine 1 [running]:
github.com/peggyjv/gravity-bridge/module/x/gravity/keeper.InitGenesis({{0x104a2fb68, 0x140001a0008}, {0x104a58420, 0x1400059a700}, {{0x0, 0x0}, {0x14000ebc370, 0xb}, 0x1d8a80, {0x0, ...}, ...}, ...}, ...)
	github.com/peggyjv/gravity-bridge/module@v0.3.3/x/gravity/keeper/genesis.go:53 +0x7ec
github.com/peggyjv/gravity-bridge/module/x/gravity.AppModule.InitGenesis({{}, {{0x104a584a0, 0x14001154f20}, {0x1049fc6f0, 0x140001f7930}, {{0x104a540e8, 0x14000eb0250}, 0x14000220020, {0x1049fc6f0, 0x140001f78d0}, ...}, ...}, ...}, ...)
	github.com/peggyjv/gravity-bridge/module@v0.3.3/x/gravity/module.go:142 +0xd0
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0x140011e0bd0, {{0x104a2fb68, 0x140001a0008}, {0x104a58420, 0x1400059a700}, {{0x0, 0x0}, {0x14000ebc370, 0xb}, 0x1d8a80, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/types/module/module.go:307 +0x1fc
github.com/peggyjv/sommelier/app.(*SommelierApp).InitChainer(0x140000f1600, {{0x104a2fb68, 0x140001a0008}, {0x104a58420, 0x1400059a700}, {{0x0, 0x0}, {0x14000ebc370, 0xb}, 0x1d8a80, ...}, ...}, ...)
	github.com/peggyjv/sommelier/app/app.go:551 +0x104
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0x140002371e0, {{0x0, 0xed8d15e70, 0x0}, {0x14000ebc370, 0xb}, 0x14000d5a860, {0x14001154840, 0x7, 0x7}, ...})
	github.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:62 +0x2e0
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0x1400019f560, {{0x0, 0xed8d15e70, 0x0}, {0x14000ebc370, 0xb}, 0x14000d5a860, {0x14001154840, 0x7, 0x7}, ...})
	github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x110
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x14000eb18d0, {{0x0, 0xed8d15e70, 0x0}, {0x14000ebc370, 0xb}, 0x14000d5a860, {0x14001154840, 0x7, 0x7}, ...})
	github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x50
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0x14000d73d80, {{{0xb, 0x0}, {0x1041aaae6, 0x7}}, {0x14000ebc370, 0xb}, 0x1d8a80, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0xc48
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0x14000d73d80, {0x104a59720, 0x14000033110})
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x400
github.com/tendermint/tendermint/node.doHandshake({0x104a52598, 0x14000eb0620}, {{{0xb, 0x0}, {0x1041aaae6, 0x7}}, {0x14000ebc370, 0xb}, 0x1d8a80, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x114
github.com/tendermint/tendermint/node.NewNode(0x140011b9680, {0x104a0c828, 0x14000d5cf00}, 0x14000f41940, {0x1049eede0, 0x140001ebd70}, 0x14000f419a0, 0x1049c7bd0, 0x14000f41b30, {0x104a308f8, ...}, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x510
github.com/cosmos/cosmos-sdk/server.startInProcess(0x1400125a620, {{0x0, 0x0, 0x0}, {0x104a66f18, 0x14001271e30}, {0x0, 0x0}, {0x104a38978, 0x14001179c40}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:263 +0x7c0
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0x140011f9b80, {0x1058f8f18, 0x0, 0x0})
	github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:129 +0x144
github.com/spf13/cobra.(*Command).execute(0x140011f9b80, {0x1058f8f18, 0x0, 0x0})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x140010fcf00)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x140010fcf00, {0x1400117ecc0, 0x1e})
	github.com/cosmos/cosmos-sdk@v0.44.5/server/cmd/execute.go:36 +0x23c
main.main()
	github.com/peggyjv/sommelier/cmd/sommelier/main.go:14 +0x3c
```

**Comment by EricBolten** [comment]
Mentioning it here too, here is a PR that will merge into this PR branch to replace the null eth signatures with "unused": https://github.com/PeggyJV/SommelierNetwork/pull/40

And the associated bridge PR to deal with and test for this issue:
https://github.com/PeggyJV/gravity-bridge/pull/333

**Comment by EricBolten** [comment]
If my understanding of the Gravity ID for the contract is correct, we'll probably want to update that as well here and when we deploy the new contract. Should we use the chain ID?

**Pull request merged**
